require "digest/md5"

require_relative "features/support/libs/mongo"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))

  users = [
    { name: "Alexandre Nunes", email: "alexandrenunes@gmail.com", password: to_md5("Teste@123") },
    { name: "Alexandre Filho", email: "alexandrefilho@gmail.com", password: to_md5("Teste@123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  #h "cucumber"
end

task :hmg_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))

  users = [
    { name: "Alexandre Nunes", email: "alexandrenunes@gmail.com", password: to_md5("Teste@123") },
    { name: "Alexandre Filho", email: "alexandrefilho@gmail.com", password: to_md5("Teste@123") },
    { name: "Murillo Nunes", email: "murillo@gmail.com", password: to_md5("Teste@123") },
  ]

  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)
end
